Up

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,9 +10,9 @@ jobs:
             mysql:
                 image: mysql:latest
                 env:
-                    MYSQL_ALLOW_EMPTY_PASSWORD: true
-                    MYSQL_ROOT_PASSWORD: password
-                    MYSQL_DATABASE: sf6-webapp-test
+                    MYSQL_ALLOW_EMPTY_PASSWORD: false
+                    MYSQL_ROOT_PASSWORD: symfony
+                    MYSQL_DATABASE: symfony
                 ports:
                     - 3306/tcp
                 options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
@@ -72,11 +72,15 @@ jobs:
             - name: Lint Doctrine entities
               run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
 
-            - name: PHP Unit
-              env:
-                  DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/sf6-webapp-test?serverVersion=8&charset=utf8mb4
+            - name: Run Migration && Load Fixtures
               run: |
-                  ./bin/console d:d:c --if-exist
-                  ./bin/console d:m:m --no-interaction
-                  ./bin/console d:f:l --no-interaction
-                  ./bin/phpunit
+                  ./bin/console doctrine:database:drop --if-exists --force --env=test
+                  ./bin/console doctrine:database:create --if-not-exists --env=test
+                  ./bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
+                  ./bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
+                  ./bin/console doctrine:fixtures:load --no-interaction
+              env:
+                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+
+            - name: PHP Unit
+              run: ./bin/phpunit
